<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "js_bmi_calculator"
 *
 * Auto generated by Extension Builder 2016-05-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'BMI Calculator',
	'description' => 'The body mass index (BMI) or Quetelet index is a value derived from the mass (weight) and height of an individual.',
	'category' => 'plugin',
	'author' => 'Jainish Senjaliya',
	'author_email' => 'jainishsenjaliya@gmail.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.0.4',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0 - 8.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);